services:
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://simulai_user:simulai_pass@postgres:5432/simulai_db
      - ENVIRONMENT=development
      - DEBUG=True
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - simulai-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=simulai_db
      - POSTGRES_USER=simulai_user
      - POSTGRES_PASSWORD=simulai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simulai-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - simulai-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Frontend React+Vite (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_SUPABASE_URL=https://rctoeldueklgtotkaypg.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdG9lbGR1ZWtsZ3RvdGtheXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTMyNzMsImV4cCI6MjA2NzU4OTI3M30.QVaQjfKn3TAm3UIPrUZYIbM_kxkZwdzhJyNm2d0Ph9c
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - simulai-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - simulai-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  simulai-network:
    driver: bridge
